- name: TELEGRAM DEBUG success_total
  ansible.builtin.debug:
    msg: "{{ success_total }}"
  tags: [never, debug]

- name: TELEGRAM Сформировать текст для Telegram (HTML)
  delegate_to: localhost
  ansible.builtin.set_fact:
    telegram_msg: |-
      <b>Обновления завершены</b>
      {% for h in groups['all'] if h != 'localhost' -%}
      {% set items = hostvars[h].success_items | default([]) -%}
      {% if items | length > 0 -%}
      <b>{{ h
            | regex_replace('&','&amp;')
            | regex_replace('<','&lt;')
            | regex_replace('>','&gt;') }}</b>:
      <i>Установлено/обновлено</i>:
      {% for it in items -%}
      • {{ it
            | regex_replace('&','&amp;')
            | regex_replace('<','&lt;')
            | regex_replace('>','&gt;') }}
      {% endfor -%}
      {% endif -%}
      {% endfor -%}
  tags: [always]

- name: DEBUG telegram_msg
  ansible.builtin.debug:
    msg: "{{ telegram_msg }}"
  tags: [never, debug]

- name: TELEGRAM Отправить сообщение в Telegram
  delegate_to: localhost
  community.general.telegram:
    token: "{{ telegram_token }}"
    api_args:
      chat_id: "{{ telegram_chat_id }}"
      text: "{{ telegram_msg | trim }}"
      parse_mode: "HTML"
      disable_web_page_preview: true
      disable_notification: true
  when: (success_total | int) > 0
  tags: [always]
